version: "3.8"
services:

  reverse-proxy:
    image: nginx:stable-alpine
    volumes:
      - ./infra/nginx:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - gateway
    networks:
      - aesp-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - aesp-net

  gateway:
    build:
      context: ./services/gateway
      dockerfile: Dockerfile
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - auth
      - users
    networks:
      - aesp-net

  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    environment:
      - PORT=4001
      - DATABASE_URL=postgres://postgres:password@auth-db:5432/authdb
      - JWT_SECRET=change-me
      - REDIS_URL=redis://redis:6379
    depends_on:
      - auth-db
      - redis
    networks:
      - aesp-net
    ports:
      - "4001:4001"

  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile
    environment:
      - PORT=4002
      - DATABASE_URL=postgres://postgres:password@users-db:5432/usersdb
    depends_on:
      - users-db
    networks:
      - aesp-net
    ports:
      - "4002:4002"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - aesp-net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - aesp-net

  auth-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authdb
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - aesp-net

  users-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: usersdb
    volumes:
      - users-db-data:/var/lib/postgresql/data
    networks:
      - aesp-net

volumes:
  auth-db-data:
  users-db-data:

networks:
  aesp-net:
    driver: bridge
